name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0  
  equatable: ^2.0.7     
  dartz: ^0.10.1        
  get_it: ^8.0.2        
  adaptive_theme: ^3.6.0              
  flutter_screenutil: ^5.9.3          
  flutter_animate: ^4.5.2             
  animated_custom_dropdown: ^3.1.1    
  shimmer: ^3.0.0                     
  flutter_svg: ^2.0.16                
  cached_network_image: ^3.4.1        
  lottie: ^3.1.3                           
  dio: ^5.7.0                         
  pretty_dio_logger: ^1.4.0           
  http_parser: ^4.1.2                 
  hive: ^2.0.4                        
  hive_flutter: ^1.1.0                
  path_provider: ^2.1.5               
  path: ^1.9.0                        
  flutter_image_compress: ^2.3.0      
  image_picker: ^1.1.2                
  file_picker: ^10.2.0                
  mime: ^2.0.0                        
  intl: ^0.20.2                       
  haptic_feedback: ^0.5.1+1           
  uuid: ^4.5.1                        
  internet_connection_checker_plus: ^2.7.1  
  flutter_launcher_icons: ^0.14.3     
  flutter_native_splash: ^2.4.4       
  permission_handler: ^12.0.1         
  pin_code_fields: ^8.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.1.2
  hive_generator: ^2.0.1



flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lotties/
    - assets/translation/



flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.jpg"
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.jpg
  android_12:
    image: assets/images/logo.jpg
    icon_background_color: "#ffffff"
    branding_mode: none