name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  adaptive_theme: ^3.6.0
  animated_custom_dropdown: ^3.1.1
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.7
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.0
  flutter_image_compress: ^2.3.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  get_it: ^8.0.2
  haptic_feedback: ^0.5.1+1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http_parser: ^4.1.2
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  internet_connection_checker_plus: ^2.7.1
  intl: ^0.20.2
  lottie: ^3.1.3
  mime: ^2.0.0
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  pin_code_fields: ^8.0.1
  pretty_dio_logger: ^1.4.0
  shimmer: ^3.0.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.1.2
  flutter_lints: ^5.0.0
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lotties/
    - assets/translation/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.jpg"
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/logo.jpg"
    background_color: "#ffffff"
    theme_color: "#ffffff"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.jpg
  android_12:
    image: assets/images/logo.jpg
    icon_background_color: "#ffffff"
    branding_mode: none
